### ISSUE TITLE
Feature request: host on something

### ISSUE THREAD

**Issue by AlishahMughal123** [favours-io/favours#16]
Hello mate,

suggestion: why you don`t host it on somewhere, so it`ll be easy to see & would be fun to add more feature .

Thanks

**Comment by BrianRuizy** [comment]
Hi @AlishahMughal123 !
I had it on Linode Linux server, but recently removed it. 
I am going to move it to AWS maybe

**Comment by AlishahMughal123** [comment]
cool that would be great :)
